### ISSUE TITLE
无法导入zdic_cibs数据

### ISSUE THREAD

**Issue by so1ar** [mozillazg/pypinyin-dict#3]
![1660876836_grim](https://user-images.githubusercontent.com/54471528/185531273-edc11c3a-3630-42d8-b4be-a18438e8bcef.png)

目前发现zdic_cibs和large_pinyin这两个数据过大，导入的时候会发生错误

**Comment by so1ar** [comment]
尝试把 zdic_cibs.py 拆分成了两个文件，分两次导入，可以正常使用

**Comment by mozillazg** [comment]
@so1ar 感谢反馈 ❤️
