### ISSUE TITLE
   from pypinyin_dict.phrase_pinyin_data import large_pinyin OverflowError: line number table is too long

### ISSUE THREAD

**Issue by jinfagang** [mozillazg/pypinyin-dict#5]
from pypinyin_dict.phrase_pinyin_data import large_pinyin
OverflowError: line number table is too long

**Comment by mozillazg** [comment]
@jinfagang 感谢反馈。看起来跟 https://github.com/mozillazg/pypinyin-dict/issues/3 是同样的问题。

**Comment by jinfagang** [comment]
@mozillazg to be more specific, this issue happens always on python above 3.10

Please consider made 2 files seperated in offical release? Users will always get this error if doesn't update for compatable with python3.10+

**Comment by mozillazg** [comment]
看了一下，这个问题是 Python 3.10 的 bug 导致的（只有这个版本的 Python 有这个问题）： https://github.com/python/cpython/issues/93964

**Comment by jinfagang** [comment]
thank u!
